src/Entity/AbstractOrder.php
<?php

namespace Kisphp\ShopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\ShopBundle\StateMachine\StateMachineInterface;
use Kisphp\Utils\Status;

/**
 * @ORM\Table(name="orders", options={"colate": "utf8_general_ci", "charset": "utf8"})
 * @ORM\HasLifecycleCallbacks()
 * @ORM\MappedSuperclass()
 */
abstract class AbstractOrder implements KisphpEntityInterface, StateMachineInterface
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $registered;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"default": Kisphp\Utils\Status::ACTIVE})
     */
    protected $status = Status::INACTIVE;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $customer_type;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $phone;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $city;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $address;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true, options={"collation": "utf8mb4_bin"})
     */
    protected $comments;

    /**
     * @var string
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $total_price;

    /**
     * @var array|\Doctrine\Common\Collections\ArrayCollection 
     */
    protected $order_items = [];

    public function __construct()
    {
        $this->order_items = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     */
    public function updateModifiedDatetime()
    {
        if ($this->registered === null) {
            $this->setRegistered(new \DateTime());
        }
    }

    /**
     * @return string
     */
    public function getTotalPrice()
    {
        return $this->total_price;
    }

    /**
     * @param string $total_price
     */
    public function setTotalPrice($total_price)
    {
        $this->total_price = $total_price;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return \DateTime
     */
    public function getRegistered()
    {
        return $this->registered;
    }

    /**
     * @param \DateTime $registered
     */
    public function setRegistered($registered)
    {
        $this->registered = $registered;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @param AbstractOrderItem $orderItem
     */
    public function addOrderItem(AbstractOrderItem $orderItem)
    {
        $this->order_items[] = $orderItem;
    }

    /**
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getOrderItems()
    {
        return $this->order_items;
    }

    /**
     * @return string
     */
    public function getCustomerType()
    {
        return $this->customer_type;
    }

    /**
     * @param $customer_type
     */
    public function setCustomerType($customer_type)
    {
        $this->customer_type = $customer_type;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param $comments
     */
    public function setComments($comments)
    {
        $this->comments = $comments;
    }
}

src/Entity/Product.php
<?php

namespace Kisphp\ShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\Entity\ToggleableInterface;
use Kisphp\Utils\Status;
use Kisphp\Utils\Strings;

/**
 * @ORM\Table(name="products", options={"colate": "utf8_general_ci", "charset": "utf8"})
 * @ORM\Entity(repositoryClass="Kisphp\ShopBundle\Repository\ProductRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Product implements KisphpEntityInterface, ToggleableInterface, PriceInterface, PriceOldInterface
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     */
    protected $id_category;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $item_url;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, length=32)
     */
    protected $code;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $registered;

    /**
     * @var ProductCategory
     *
     * @ORM\ManyToOne(targetEntity="ProductCategory", inversedBy="products")
     * @ORM\JoinColumn(name="id_category", referencedColumnName="id")
     */
    protected $category;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"default": Kisphp\Utils\Status::ACTIVE})
     */
    protected $status = Status::ACTIVE;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $available_stoc;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $price;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $price_old;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $seo_title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $seo_keywords;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $seo_description;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $body;

    /**
     * @ORM\PrePersist()
     */
    public function updateModifiedDatetime()
    {
        if ($this->registered === null) {
            $this->setRegistered(new \DateTime());
        }
    }

    /**
     * @return \DateTime
     */
    public function getRegistered()
    {
        return $this->registered;
    }

    /**
     * @param \DateTime $registered
     */
    public function setRegistered($registered)
    {
        $this->registered = $registered;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
        $this->setItemUrl($title);

        if (empty($this->getSeoTitle())) {
            $this->setSeoTitle($title);
        }
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return int
     */
    public function getIdCategory()
    {
        return $this->id_category;
    }

    /**
     * @param int $id_category
     */
    public function setIdCategory($id_category)
    {
        $this->id_category = $id_category;
    }

    /**
     * @return ProductCategory
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param ProductCategory $category
     */
    public function setCategory(ProductCategory $category)
    {
        $this->category = $category;
        if ($category->getId() > 0) {
            $this->id_category = $category->getId();
        }
    }

    /**
     * @return string
     */
    public function getItemUrl()
    {
        return $this->item_url;
    }

    /**
     * @param string $item_url
     */
    public function setItemUrl($item_url)
    {
        $this->item_url = Strings::niceUrlTitle($item_url);
    }

    /**
     * @return string
     */
    public function getSeoTitle()
    {
        return $this->seo_title;
    }

    /**
     * @param string $seo_title
     */
    public function setSeoTitle($seo_title)
    {
        $this->seo_title = $seo_title;
    }

    /**
     * @return string
     */
    public function getSeoKeywords()
    {
        return $this->seo_keywords;
    }

    /**
     * @param string $seo_keywords
     */
    public function setSeoKeywords($seo_keywords)
    {
        $this->seo_keywords = $seo_keywords;
    }

    /**
     * @return string
     */
    public function getSeoDescription()
    {
        return $this->seo_description;
    }

    /**
     * @param string $seo_description
     */
    public function setSeoDescription($seo_description)
    {
        $this->seo_description = $seo_description;
    }

    /**
     * @return int
     */
    public function getAvailableStoc()
    {
        return $this->available_stoc;
    }

    /**
     * @param int $available_stoc
     */
    public function setAvailableStoc($available_stoc)
    {
        $this->available_stoc = $available_stoc;
    }

    /**
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param int $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * @return int
     */
    public function getPriceOld()
    {
        return $this->price_old;
    }

    /**
     * @param int $price_old
     */
    public function setPriceOld($price_old)
    {
        $this->price_old = $price_old;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param string $body
     */
    public function setBody($body)
    {
        $this->body = $body;
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @param string $code
     */
    public function setCode($code)
    {
        $this->code = $code;
    }
}

src/Controller/OrdersController.php
<?php

namespace Kisphp\ShopBundle\Controller;

use Kisphp\ShopBundle\Entity\AbstractOrder;
use Kisphp\ShopBundle\Form\CustomerOrderForm;
use Kisphp\ShopBundle\StateMachine\Declarations\CustomerOrderStateMachine;
use Symfony\Component\HttpFoundation\Request;
use Kisphp\FrameworkAdminBundle\Controller\AbstractController;

class OrdersController extends AbstractController
{
    const SECTION_TITLE = 'section.title.shop.customer_orders';
    const MODEL_NAME = 'model.shop.order';
    const LISTING_TEMPLATE = '@Shop/Orders/index.html.twig';
    const ENTITY_FORM_CLASS = CustomerOrderForm::class;

    /**
     * @var array
     */
    protected $section = [
        self::EDIT_PATH => 'shop_orders_edit',
        self::LIST_PATH => 'shop_orders',
        self::ADD_PATH => 'shop_orders_add',
        self::STATUS_PATH => 'shop_orders_status',
        self::DELETE_PATH => 'shop_orders_delete',
    ];

    /**
     * @param Request $request
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id = 0)
    {
        /** @var AbstractOrder $entity */
        $entity = $this->get('model.shop.order')->find($id);
        $form = $this->createEditForm($request, $id);

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->processSubmittedForm($form);
        }

        $ids = [];
        foreach ($entity->getOrderItems() as $item) {
            $ids[] = $item->getIdProduct();
        }

        $products = $this->get('model.shop.product')->getProductsByIdList($ids);

        $stateMachine = new CustomerOrderStateMachine($entity);

        return $this->render(
            '@Shop/Orders/edit.html.twig',
            [
                'id' => $id,
                'stateMachine' => $stateMachine,
                'entity' => $entity,
                'products' => $products,
                'form' => $form->createView(),
                'attached' => $this->getAttachedFiles($id),
                'section' => $this->section,
                'html_editor' => static::HTML_EDITOR_ENABLED,
                'upload_type' => static::UPLOAD_TYPE,
                'images_list_url' => $this->getImagesEditUrl($id),
                'templates' => $this->get('model.cms.template')->getTemplatesFormEditor(),
                'section_title' => static::SECTION_TITLE . (($id > 0) ? '.edit' : '.create'),
            ]
        );
    }

    /**
     * @param int $id
     * @param string $state
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function changeStateAction($id, $state)
    {
        $model = $this->get('model.shop.order');
        $order = $model->find($id);

        $sm = new CustomerOrderStateMachine($order);

        $sm->changeTransition($state);

        $model->save($order);

        return $this->redirect(
            $this->generateUrl('shop_orders_edit', [
                'id' => $order->getId(),
            ])
        );
    }

    /**
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function totalAction($id)
    {
        $this->get('model.shop.order')->recalculateTotal($id);

        return $this->redirect(
            $this->generateUrl('shop_orders_edit', ['id' => $id])
        );
    }

    /**
     * @param Request $request
     * @param $object
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    protected function createFormObject(Request $request, $object)
    {
        $form = $this->createForm(CustomerOrderForm::class, $object);
        $form->handleRequest($request);

        return $form;
    }
}

src/Resources/views/Orders/edit-item.html.twig
{% extends '@FrameworkAdmin/components/form.html.twig' %}

{% block box_header %}
    {% if entity.idOrder is defined and entity.idOrder is not none %}
        {% set order_id = entity.idOrder %}
    {% else %}
        {% set order_id = id %}
    {% endif %}
    <a href="{{ path('shop_orders_edit', {id: order_id}) }}" class="btn btn-xs btn-github"><i class="fa fa-list"></i> {{ 'btn.list' | trans }}</a>
    <a href="{{ path('shop_orders_item_add', {id: order_id}) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Add product to cart</a>
{% endblock %}

{% block body_box2 %}

    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <h3 class="box-title">{% block section_title %}{{ section_title | default('') | trans }}{% endblock %}</h3>
                </div>
                <div class="col-xs-12 col-sm-8 text-right">
                    <a href="{{ path(section.list_path) }}" class="btn btn-xs btn-github"><i class="fa fa-list"></i> {{ 'btn.list' | trans }}</a>
                    {% if section.add_path != '' %}
                        <a href="{{ path(section.add_path) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> {{ 'btn.create' | trans }}</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="box-body">

        {% block body %}
            {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

            <div class="box-body2">
                {{ form_widget(form) }}
            </div>

            <div class="box-footer">
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <input type="submit" class="btn btn-success" value="{{ 'btn.save' | trans }}">
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        {% endblock %}

        </div>
    </div>

{% endblock %}

src/Resources/views/Orders/edit.html.twig
{% extends 'FrameworkAdminBundle::layout.html.twig' %}

{% block body_box %}

    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <h3 class="box-title">{% block section_title %}{{ section_title | default('') | trans }}{% endblock %}</h3>
                </div>
                <div class="col-xs-12 col-sm-8 text-right">
                    <a href="{{ path(section.list_path) }}" class="btn btn-xs btn-github"><i class="fa fa-list"></i> {{ 'btn.list' | trans }}</a>
                    {% if section.add_path != '' %}
                        <a href="{{ path(section.add_path) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> {{ 'btn.create' | trans }}</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-sm-6">

        {% block body %}
            {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

            <div class="box-body2">
                {{ form_widget(form) }}
            </div>

            <div class="box-footer">
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <input type="submit" class="btn btn-success" value="{{ 'btn.save' | trans }}">
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        {% endblock %}

                </div>
                <div class="col-sm-6">
                    <iframe
                        width="600"
                        height="400"
                        frameborder="0" style="border:0; width: 100%;"
                        src="https://www.google.com/maps/embed/v1/place?key={{ google_maps_key }}&q={{ entity.address }} {{ entity.city }}" allowfullscreen>
                    </iframe>
                </div>
            </div>

        </div>
    </div>

    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <h3 class="box-title">Order Items</h3>
                </div>
                <div class="col-xs-12 col-sm-8 text-right">
                    {% if stateMachine.canChange %}
                    <a href="{{ path('shop_orders_item_add', {id: entity.id}) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Add product to cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="box-body">

            <table class="table table-condensed table-bordered">
            <tr>
                {% if stateMachine.canChange %}
                <th>Options</th>
                {% endif %}
                <th>Product title</th>
                <th>Product code</th>
                <th>Tax Value (%)</th>
                <th>Shipping Cost (%)</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Item total price</th>
            </tr>
            {% for item in entity.orderItems %}
            <tr>
                {% if stateMachine.canChange %}
                <td>
                    <a href="{{ path('shop_orders_item_edit', {id: item.id}) }}" class="btn btn-primary btn-xs">Edit</a>
                    <a href="" class="btn btn-danger btn-xs">Delete</a>
                </td>
                {% endif %}
                <td><a href="{{ path('shop_products_edit', {id: item.idProduct}) }}" target="_blank">{{ products[item.idProduct].title }}</a></td>
                <td>{{ products[item.idProduct].code }}</td>
                <td>{{ item.taxValue }}</td>
                <td>{{ item.shippingCost }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price | price }}</td>
                <td>{{ item.totalPrice | price }}</td>
            </tr>
            {% endfor %}
            </table>

            <div class="desp-20"></div>

            <div class="row">
                <div class="col-sm-8">
                    <a href="{{ path('shop_orders_total', {id: entity.id}) }}" class="btn-sm btn btn-primary">Recalculate total</a>
                    {% for key, sm in stateMachine.getAvailableTransitions %}
                        <a href="{{ path('shop_orders_item_status', {id: entity.id, state: key}) }}" class="btn btn-sm btn-info"><i class="fa fa-step-forward" aria-hidden="true"></i> {{ key | trans }}</a>&nbsp;
                    {% endfor %}
                </div>
                <div class="col-sm-4 text-right">
                    <h2 class="total-price">Total: {{ entity.totalPrice | price }}</h2>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/Resources/views/Orders/index.html.twig
{% extends '@FrameworkAdmin/components/listing.html.twig' %}

{% import '@FrameworkAdmin/macros/navigation-macros.html.twig' as navBtn %}
{% import '@FrameworkAdmin/macros/table-btn-macros.html.twig' as tbl %}

{% block box_header %}
    {{ navBtn.list(path(section.list_path), 'btn.list') }}
    {#{{ navBtn.create(path(section.add_path), 'btn.create') }}#}
{% endblock %}

{% block listing_table_content %}
    <thead>
    <tr>
        <th width="200">{{ 'table.header.options' | trans }}</th>
        <th width="60">{{ 'table.header.id' | trans }}</th>
        <th>{{ 'table.header.title' | trans }}</th>
        <th>{{ 'table.header.status' | trans }}</th>
        <th>{{ 'table.header.email' | trans }}</th>
        <th>{{ 'table.header.phone' | trans }}</th>
        <th>{{ 'table.header.city' | trans }}</th>
        <th>{{ 'table.header.total_price' | trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for item in items %}
        {#{{ dump(item) }}#}
        <tr id="row-{{ item.id }}" class="{{ orderItemRowClass(item) }}">
            <td>
                {{ tbl.edit(path(section.edit_path, {id: item.id})) }}
                {#{{ tbl.delete(item.id, path(section.delete_path)) }}#}
            </td>
            <td>{{ item.id }}</td>
            <td><a href="{{ path(section.edit_path, {id: item.id}) }}">{{ item.name }}</a></td>
            <td>{{ item | orderStateMachineStatus | trans }}</td>
            <td>{{ item.email }}</td>
            <td>{{ item.phone }}</td>
            <td>{{ item.city }}</td>
            {#<td><a href="{{ path(section.list_path, {c: item.idCategory}) }}">{{ item.category }}</a></td>#}
            <td>{{ item.totalPrice | default(0) | price }}</td>
            {#{{ statusToggle(item, path(section.status_path)) }}#}
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}